[package]
name = "leanvm-xmss-c"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]
test-config = []

[dependencies]
lean-multisig = { git = "https://github.com/leanEthereum/leanVM", rev = "a5909d18647de6aed38640c098d9177fab2bf36a" }
postcard = { version = "1.1", features = ["alloc"] }
rand = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ssz = { package = "ethereum_ssz", version = "0.10" }
tikv-jemallocator = { version = "0.6", optional = true }

[build-dependencies]
cbindgen = "0.27"

[profile.multisig-release]
inherits = "release"
lto = "thin"
codegen-units = 1
